language: python

python: "3.8"

tags: true

install:
  - sudo apt-get update

script:
  - pip3 install -r requirements.txt
  - bash scripts/download_weights_gen.sh
  - bash scripts/download_weights_rot.sh
